Decode JTI when available
palantir/auth-tokens pull request #27
Opened 2017-03-06 13:17 UTC by shashiadi

Add JTI and session ID to log metadata context when available.

2017-03-06 13:17 UTC, palantirtech commented
Thanks for your interest in [palantir/auth-tokens](https://github.com/palantir/auth-tokens), @shashiadi! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2017-03-07 00:13 UTC, markelliot approved these changes

2017-03-14 10:38 UTC, uschi2000 commented on auth-tokens-filter/src/main/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilter.java
> +                        MDC.put("sessionId", jwt.getUnverifiedSessionId().get());
IMO, should be called unverifiedSessionId

2017-03-14 10:38 UTC, uschi2000 commented on auth-tokens-filter/src/main/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilter.java
> +                        MDC.put("tokenId", jwt.getUnverifiedTokenId().get());
unverifiedTokenId

2017-03-14 10:40 UTC, uschi2000 requested changes

2017-03-14 10:40 UTC, uschi2000 commented on auth-tokens-filter/src/main/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilter.java
> +
remove

2017-03-14 10:40 UTC, uschi2000 commented on auth-tokens-filter/src/test/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilterTests.java
> +        assertThat(requestEvent.getValue().getMDCPropertyMap().get("tokenId"), is(TOKEN_ID));
just add these two lines to the existing test?

2017-03-14 10:50 UTC, shashiadi commented on auth-tokens-filter/src/test/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilterTests.java
> +        assertThat(requestEvent.getValue().getMDCPropertyMap().get("tokenId"), is(TOKEN_ID));
It's a different kind of token, so can either have sessionId or tokenId.

2017-03-14 10:51 UTC, uschi2000 commented on auth-tokens-filter/src/test/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilterTests.java
> +        assertThat(requestEvent.getValue().getMDCPropertyMap().get("tokenId"), is(TOKEN_ID));
oh, my bad

2017-05-31 21:01 UTC, uschi2000 commented on auth-tokens-filter/src/main/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilter.java
> +                    if (jwt.getUnverifiedSessionId().isPresent()) {
nit: let's keep these three together without line breaks (so that they all belong to the `//slf4j` comment)

2017-05-31 21:27 UTC, uschi2000 commented on auth-tokens-filter/src/test/java/com/palantir/tokens/auth/http/BearerTokenLoggingContextFilterTests.java
> +    public void testBearerTokenLogging_sessionIdAppearsInMetaDataContext() {
could you inline these tests with testBearerTokenLogging_userIdAppearsInMetaDataContext ? there's a lot of duplicate code to check basically the same thing.

2017-05-31 21:27 UTC, uschi2000 commented
two nits, otherwise I'm fine with this.

2017-06-08 13:51 UTC, uschi2000 commented
looks like this is obsolete? @diogoholanda

2017-06-08 13:52 UTC, closed without merging

2017-06-08 13:56 UTC, diogoholanda commented
Yeah, I think one of my PRs that merged actually fixed that